[project]
name = "texas-community-college-benchmarking"
version = "0.1.0"
description = "Texas Community College Benchmarking"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-duckdb>=1.10.1",
    "duckdb>=1.5.3",
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "requests>=2.32.5",
    "streamlit>=1.53.0",
]
